<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Custom Geometry Filter</title>
  <meta name="description" content="```cspartial class Examples{  private static double m_tolerance;  public static Result CustomGeometryFilter(RhinoDoc doc)  {    m_tolerance = doc.ModelAbsolu...">

  <!-- OpenGraph for Facebook, Twitter, Slack unfurling -->
  <meta property="og:type" content="website" />
  <meta property="og:url" content="/samples/rhinocommon/custom_geometry_filter/" />
  <meta property="og:title" content="Custom Geometry Filter" />
  <meta property="og:description" content="Demonstrates how to create a specialized GetObject with a custom geometry filter." />
  <meta property=”og:site_name” content="developer.rhino3d.com"/>
  <meta property=”og:image” content="/wip/images/rhinodev_logo_unfurl.png"/>

  <!-- twitter card tags additive with the og: tags -->
  <meta name="twitter:domain" value="developer.rhino3d.com" />
  <meta name="twitter:title" value="Custom Geometry Filter" />
  <meta name="twitter:description" value="Demonstrates how to create a specialized GetObject with a custom geometry filter." />
  
    
      <meta name="twitter:image" content="/wip/images/rhinodev_logo_unfurl.png" />
    
  
  <meta name="twitter:url" value="http://developer.rhino3d.com" />
  
  <meta name="twitter:label1" value="Platform(s)" />
  <meta name="twitter:data1" value="Windows, Mac" />
  
  
  <meta name="twitter:label2" value="Language(s)" />
  <meta name="twitter:data2" value="C#, Python, VB" />
  

  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/github.min.css">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/vbnet.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <!-- Overridden theme -->
  <link rel="stylesheet" href="/wip/css/main.css">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <!-- Bootstrap override -->
  <link rel="stylesheet" href="/wip/css/bootstrap-override.css">

  <link rel="canonical" href="http://developer.rhino3d.com/wip/samples/rhinocommon/custom_geometry_filter/">
  <link rel="alternate" type="application/rss+xml" title="Rhino Developer Docs" href="http://developer.rhino3d.com/wip/feed.xml" />

  <link rel="shortcut icon" href="http://developer.rhino3d.com/favicon.ico?v=2" />
  <!-- Saving bookmarks to mobile devices -->
  <!-- For non-Retina (@1× display) iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="/wip/images/apple-touch-icon-precomposed.png"><!-- 57×57px -->
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/wip/images/apple-touch-icon-72x72-precomposed.png">
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/wip/images/apple-touch-icon-76x76-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/wip/images/apple-touch-icon-114x114-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/wip/images/apple-touch-icon-120x120-precomposed.png">
  <!-- For iPad with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/wip/images/apple-touch-icon-144x144-precomposed.png">
  <!-- For iPad with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/wip/images/apple-touch-icon-152x152-precomposed.png">
  <!-- For iPhone 6 Plus with @3× display: -->
  <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/wip/images/apple-touch-icon-180x180-precomposed.png">
  <!-- For Chrome for Android: -->
  <link rel="icon" sizes="192x192" href="images/touch-icon-192x192.png">

  <!-- Diable crawling until this version is the stable version -->
  <meta name="robots" content="noindex" />
</head>


  <body>

    <!-- Google Tag Manager **This belongs right after the <body> tag**-->
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MWMDKN"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MWMDKN');
    </script>
    <!-- End Google Tag Manager -->


    
<div class="version-banner">
    Hey, you're viewing the <strong>wip</strong> version of this page!
    <script>
      function() {
        var splitPath = window.location.pathname.split("/");
  	    var nonWipURL = "/" + splitPath.splice(2,splitPath.length-2).join("/");

  	    $.get(nonWipURL).fail(function ()
  	    {
          <a href="">View the current site instead.</a>
        } else {
          <a href="/samples/rhinocommon/custom_geometry_filter/">View the current version instead.</a>
        });
      }
    </script>
</div>



    <div class="container">

      <header class="site-header">


    <a class="site-title" href="/wip/"><img src="/wip/images/rhinodevlogo148x128.png" alt="Rhino Developer Docs" height="48" width="56"></a><a class="site-title" href="/wip/">Rhino Developer Docs</a>

    <nav class="site-nav">
      <img class="menu-icon" src="/wip/images/gi.svg">
      
      <div class="trigger">
      	<!--<a class="page-link" href="/wip/">Welcome</a>-->
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
        
          
            
              
                <a class="page-link" href="/wip/guides/">Guides</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/wip/api/">API</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/wip/samples/">Samples</a>
              
            
          
        
          
            
          
        
        <a class="page-link" href="http://discourse.mcneel.com/c/rhino-developer">Forums</a>
        <!-- Google Search Engine -->
        <!-- TODO Move to this site back into the Mcneel search, or use a simple site only search for results -->
        <div id="sitesearch">
            <!-- Google CSE Search Box Begins  -->
            <!-- Use of this code assumes agreement with the Google Custom Search Terms of Service. -->
            <!-- The terms of service are available at https://www.google.com/cse/docs/tos.html -->
            <form id="cref" action="/wip/search-results.html">
                <input type="hidden" name="cref" value="007988927381198593803:mcq6pshqsn8" />
                <input id="searchtext" type="text" name="q" size="24" value="" placeholder="search" />
                <input class="searchBox" type="submit" name="sa" size="2" value=" " />
            </form>
        <!-- Google CSE Search Box Ends -->
        </div>
        <!--End of Google Search Engine -->
      </div>
    </nav>

</header>


      <div class="page-content">
        <!--div class="wrapper"-->
          <h3>Custom Geometry Filter</h3>

<p>Demonstrates how to create a specialized GetObject with a custom geometry filter.</p>

<ul class="nav nav-pills">
  <li class="active"><a href="#cs" data-toggle="pill">C#</a></li>
  <li><a href="#vb" data-toggle="pill">VB.NET</a></li>
  <li><a href="#py" data-toggle="pill">Python</a></li>
</ul>

<div class="tab-content">
  <div class="language-cs tab-pane fade in active highlighter-rouge" id="cs"><pre class="highlight"><code><span class="k">partial</span> <span class="k">class</span> <span class="nc">Examples</span>
<span class="p">{</span>
  <span class="k">private</span> <span class="k">static</span> <span class="kt">double</span> <span class="n">m_tolerance</span><span class="p">;</span>
  <span class="k">public</span> <span class="k">static</span> <span class="n">Result</span> <span class="nf">CustomGeometryFilter</span><span class="p">(</span><span class="n">RhinoDoc</span> <span class="n">doc</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="n">m_tolerance</span> <span class="p">=</span> <span class="n">doc</span><span class="p">.</span><span class="n">ModelAbsoluteTolerance</span><span class="p">;</span>

    <span class="c1">// only use a custom geometry filter if no simpler filter does the job
</span>
    <span class="c1">// only curves
</span>    <span class="n">var</span> <span class="n">gc</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">GetObject</span><span class="p">();</span>
    <span class="n">gc</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"select curve"</span><span class="p">);</span>
    <span class="n">gc</span><span class="p">.</span><span class="n">GeometryFilter</span> <span class="p">=</span> <span class="n">ObjectType</span><span class="p">.</span><span class="n">Curve</span><span class="p">;</span>
    <span class="n">gc</span><span class="p">.</span><span class="nf">DisablePreSelect</span><span class="p">();</span>
    <span class="n">gc</span><span class="p">.</span><span class="n">SubObjectSelect</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">gc</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gc</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gc</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="k">null</span> <span class="p">==</span> <span class="n">gc</span><span class="p">.</span><span class="nf">Object</span><span class="p">(</span><span class="m">0</span><span class="p">).</span><span class="nf">Curve</span><span class="p">())</span>
      <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>
    <span class="n">Rhino</span><span class="p">.</span><span class="n">RhinoApp</span><span class="p">.</span><span class="nf">WriteLine</span><span class="p">(</span><span class="s">"curve was selected"</span><span class="p">);</span>

    <span class="c1">// only closed curves
</span>    <span class="n">var</span> <span class="n">gcc</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">GetObject</span><span class="p">();</span>
    <span class="n">gcc</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"select closed curve"</span><span class="p">);</span>
    <span class="n">gcc</span><span class="p">.</span><span class="n">GeometryFilter</span> <span class="p">=</span> <span class="n">ObjectType</span><span class="p">.</span><span class="n">Curve</span><span class="p">;</span>
    <span class="n">gcc</span><span class="p">.</span><span class="n">GeometryAttributeFilter</span> <span class="p">=</span> <span class="n">GeometryAttributeFilter</span><span class="p">.</span><span class="n">ClosedCurve</span><span class="p">;</span>
    <span class="n">gcc</span><span class="p">.</span><span class="nf">DisablePreSelect</span><span class="p">();</span>
    <span class="n">gcc</span><span class="p">.</span><span class="n">SubObjectSelect</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">gcc</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gcc</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gcc</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="k">null</span> <span class="p">==</span> <span class="n">gcc</span><span class="p">.</span><span class="nf">Object</span><span class="p">(</span><span class="m">0</span><span class="p">).</span><span class="nf">Curve</span><span class="p">())</span>
      <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>
    <span class="n">Rhino</span><span class="p">.</span><span class="n">RhinoApp</span><span class="p">.</span><span class="nf">WriteLine</span><span class="p">(</span><span class="s">"closed curve was selected"</span><span class="p">);</span>

    <span class="c1">// only circles with a radius of 10
</span>    <span class="n">var</span> <span class="n">gcc10</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">GetObject</span><span class="p">();</span>
    <span class="n">gcc10</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"select circle with radius of 10"</span><span class="p">);</span>
    <span class="n">gc</span><span class="p">.</span><span class="n">GeometryFilter</span> <span class="p">=</span> <span class="n">ObjectType</span><span class="p">.</span><span class="n">Curve</span><span class="p">;</span>
    <span class="n">gcc10</span><span class="p">.</span><span class="nf">SetCustomGeometryFilter</span><span class="p">(</span><span class="n">CircleWithRadiusOf10GeometryFilter</span><span class="p">);</span> <span class="c1">// custom geometry filter
</span>    <span class="n">gcc10</span><span class="p">.</span><span class="nf">DisablePreSelect</span><span class="p">();</span>
    <span class="n">gcc10</span><span class="p">.</span><span class="n">SubObjectSelect</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">gcc10</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gcc10</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gcc10</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="k">null</span> <span class="p">==</span> <span class="n">gcc10</span><span class="p">.</span><span class="nf">Object</span><span class="p">(</span><span class="m">0</span><span class="p">).</span><span class="nf">Curve</span><span class="p">())</span>
      <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>
    <span class="n">RhinoApp</span><span class="p">.</span><span class="nf">WriteLine</span><span class="p">(</span><span class="s">"circle with radius of 10 was selected"</span><span class="p">);</span>

    <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="k">private</span> <span class="k">static</span> <span class="kt">bool</span> <span class="nf">CircleWithRadiusOf10GeometryFilter</span> <span class="p">(</span><span class="n">Rhino</span><span class="p">.</span><span class="n">DocObjects</span><span class="p">.</span><span class="n">RhinoObject</span> <span class="n">rhObject</span><span class="p">,</span> <span class="n">GeometryBase</span> <span class="n">geometry</span><span class="p">,</span>
    <span class="n">ComponentIndex</span> <span class="n">componentIndex</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="kt">bool</span> <span class="n">is_circle_with_radius_of10</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">Circle</span> <span class="n">circle</span><span class="p">;</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">geometry</span> <span class="k">is</span> <span class="n">Curve</span> <span class="p">&amp;&amp;</span> <span class="p">(</span><span class="n">geometry</span> <span class="k">as</span> <span class="n">Curve</span><span class="p">).</span><span class="nf">TryGetCircle</span><span class="p">(</span><span class="k">out</span> <span class="n">circle</span><span class="p">))</span>
      <span class="n">is_circle_with_radius_of10</span> <span class="p">=</span> <span class="n">circle</span><span class="p">.</span><span class="n">Radius</span> <span class="p">&lt;=</span> <span class="m">10.0</span> <span class="p">+</span> <span class="n">m_tolerance</span> <span class="p">&amp;&amp;</span> <span class="n">circle</span><span class="p">.</span><span class="n">Radius</span> <span class="p">&gt;=</span> <span class="m">10.0</span> <span class="p">-</span> <span class="n">m_tolerance</span><span class="p">;</span>
    <span class="k">return</span> <span class="n">is_circle_with_radius_of10</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
</div>

<pre class="tab-pane fade in" id="vb"><code class="language-vbnet">Partial Friend Class Examples
  Private Shared m_tolerance As Double
  Public Shared Function CustomGeometryFilter(ByVal doc As RhinoDoc) As Result
	m_tolerance = doc.ModelAbsoluteTolerance

	' only use a custom geometry filter if no simpler filter does the job

	' only curves
	Dim gc = New GetObject()
	gc.SetCommandPrompt("select curve")
	gc.GeometryFilter = ObjectType.Curve
	gc.DisablePreSelect()
	gc.SubObjectSelect = False
	gc.Get()
	If gc.CommandResult() &lt;&gt; Result.Success Then
	  Return gc.CommandResult()
	End If
	If Nothing Is gc.Object(0).Curve() Then
	  Return Result.Failure
	End If
	Rhino.RhinoApp.WriteLine("curve was selected")

	' only closed curves
	Dim gcc = New GetObject()
	gcc.SetCommandPrompt("select closed curve")
	gcc.GeometryFilter = ObjectType.Curve
	gcc.GeometryAttributeFilter = GeometryAttributeFilter.ClosedCurve
	gcc.DisablePreSelect()
	gcc.SubObjectSelect = False
	gcc.Get()
	If gcc.CommandResult() &lt;&gt; Result.Success Then
	  Return gcc.CommandResult()
	End If
	If Nothing Is gcc.Object(0).Curve() Then
	  Return Result.Failure
	End If
	Rhino.RhinoApp.WriteLine("closed curve was selected")

	' only circles with a radius of 10
	Dim gcc10 = New GetObject()
	gcc10.SetCommandPrompt("select circle with radius of 10")
	gc.GeometryFilter = ObjectType.Curve
	gcc10.SetCustomGeometryFilter(AddressOf CircleWithRadiusOf10GeometryFilter) ' custom geometry filter
	gcc10.DisablePreSelect()
	gcc10.SubObjectSelect = False
	gcc10.Get()
	If gcc10.CommandResult() &lt;&gt; Result.Success Then
	  Return gcc10.CommandResult()
	End If
	If Nothing Is gcc10.Object(0).Curve() Then
	  Return Result.Failure
	End If
	RhinoApp.WriteLine("circle with radius of 10 was selected")

	Return Result.Success
  End Function

  Private Shared Function CircleWithRadiusOf10GeometryFilter(ByVal rhObject As Rhino.DocObjects.RhinoObject, ByVal geometry As GeometryBase, ByVal componentIndex As ComponentIndex) As Boolean
	Dim is_circle_with_radius_of10 As Boolean = False
	Dim circle As Circle = Nothing
	If TypeOf geometry Is Curve AndAlso (TryCast(geometry, Curve)).TryGetCircle(circle) Then
	  is_circle_with_radius_of10 = circle.Radius &lt;= 10.0 + m_tolerance AndAlso circle.Radius &gt;= 10.0 - m_tolerance
	End If
	Return is_circle_with_radius_of10
  End Function
End Class
</code></pre>

<div class="language-python tab-pane fade in highlighter-rouge" id="py"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">rhinoscriptsyntax</span> <span class="kn">as</span> <span class="nn">rs</span>
<span class="kn">from</span> <span class="nn">scriptcontext</span> <span class="kn">import</span> <span class="o">*</span>
<span class="kn">import</span> <span class="nn">Rhino</span>

<span class="k">def</span> <span class="nf">circleWithRadiusOf10GeometryFilter</span> <span class="p">(</span><span class="n">rhObject</span><span class="p">,</span> <span class="n">geometry</span><span class="p">,</span> <span class="n">componentIndex</span><span class="p">):</span>
  <span class="n">isCircleWithRadiusOf10</span> <span class="o">=</span> <span class="bp">False</span>
  <span class="n">c</span> <span class="o">=</span> <span class="n">rs</span><span class="o">.</span><span class="n">coercecurve</span><span class="p">(</span><span class="n">geometry</span><span class="p">)</span>
  <span class="k">if</span> <span class="n">c</span><span class="p">:</span>
    <span class="n">b</span><span class="p">,</span> <span class="n">circle</span> <span class="o">=</span> <span class="n">c</span><span class="o">.</span><span class="n">TryGetCircle</span><span class="p">()</span>
  <span class="k">if</span> <span class="n">b</span><span class="p">:</span>
    <span class="n">isCircleWithRadiusOf10</span> <span class="o">=</span> <span class="n">circle</span><span class="o">.</span><span class="n">Radius</span> <span class="o">&lt;=</span> <span class="mf">10.0</span> <span class="o">+</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">RhinoMath</span><span class="o">.</span><span class="n">ZeroTolerance</span> <span class="ow">and</span> <span class="n">circle</span><span class="o">.</span><span class="n">Radius</span> <span class="o">&gt;=</span> <span class="mf">10.0</span> <span class="o">-</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">RhinoMath</span><span class="o">.</span><span class="n">ZeroTolerance</span>
  <span class="k">return</span> <span class="n">isCircleWithRadiusOf10</span>

<span class="k">def</span> <span class="nf">RunCommand</span><span class="p">():</span>
  <span class="c"># only use a custom geometry filter if no simpler filter does the job</span>

  <span class="c"># for curves - only a simple filter is needed</span>
  <span class="k">if</span> <span class="n">rs</span><span class="o">.</span><span class="n">GetObject</span><span class="p">(</span><span class="s">"select curve"</span><span class="p">,</span> <span class="n">rs</span><span class="o">.</span><span class="nb">filter</span><span class="o">.</span><span class="n">curve</span><span class="p">):</span> <span class="c">#Rhino.DocObjects.ObjectType.Curve):</span>
    <span class="k">print</span> <span class="s">"curve vas selected"</span>

  <span class="c"># for circles with a radius of 10 - a custom geometry filter is needed</span>
  <span class="k">if</span> <span class="n">rs</span><span class="o">.</span><span class="n">GetObject</span><span class="p">(</span><span class="s">"select circle with radius of 10"</span><span class="p">,</span> <span class="n">rs</span><span class="o">.</span><span class="nb">filter</span><span class="o">.</span><span class="n">curve</span><span class="p">,</span> <span class="bp">False</span><span class="p">,</span> <span class="bp">False</span><span class="p">,</span> <span class="n">circleWithRadiusOf10GeometryFilter</span><span class="p">):</span>
      <span class="k">print</span> <span class="s">"circle with radius of 10 was selected"</span>

<span class="k">if</span> <span class="n">__name__</span><span class="o">==</span><span class="s">"__main__"</span><span class="p">:</span>
  <span class="n">RunCommand</span><span class="p">()</span>
</code></pre>
</div>

</div>

        <!--/div-->
      </div>

      <footer class="site-footer">

  <div class="wrapper">

    <div class="footer-col-wrapper">

      
        <div class="row">
          <div class="col-md-4">
            <p class="text">Author: <a href="mailto:steve@mcneel.com">steve@mcneel.com</a></p>
          </div>
          <div class="col-md-4 text-center">
            <span class="icon  icon--github">
              <svg viewBox="0 0 16 16">
                <path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/>
              </svg>
            </span>
            <a href="https://github.com/mcneel/developer-rhino3d-com/blob/wip/_samples/rhinocommon/custom_geometry_filter.md" target="_blank">Edit page on GitHub</a>
          </div>
            <div class="col-md-4">
              <span class="pull-right">
                <span class="glyphicon glyphicon-cog"></span>&nbsp;<a href="/wip/admin">Admin</a>
              </span>
            </div>
        </div>

        <div class="row text-center">
          © 1997 - 2016 Robert McNeel &amp; Associates
        </div>

      

    </div>

  </div>

  <script>
    if (navigator.appVersion.indexOf("Win")!=-1)
    {
      var body = document.getElementsByTagName("body");
      body[0].style.fontWeight = '400';
    }
  </script>

</footer>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- MathJax -->
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    <script type="text/javascript">
    $('body').scrollspy({
        target: '.bs-docs-sidebar',
        offset: 150 /* fixed header is about 40px high */
    });
    </script>
  </body>

</html>
